# Generated by Django 5.2.6 on 2025-10-01 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('state', 'Государственная'), ('honorary', 'Почётное звание (Ардак наам)'), ('department', 'Ведомственная')], max_length=20, verbose_name='Категория награды')),
                ('state_award', models.CharField(blank=True, choices=[('hero', 'Кыргыз Республикасынын Баатыры'), ('manas', 'Орден "Манас"'), ('kurmanjan', 'Орден "Курманжан Датка"'), ('baatyr_ene', 'Орден "Баатыр эне"'), ('danaker', 'Орден "Данакер"'), ('erdik', 'Орден "Эрдик"'), ('dank', 'Медаль "Данк"'), ('ene_danky', 'Медаль "Эне данкы"'), ('kujurmon', 'Медаль "Кужурмож кызмат отогондугу учун"'), ('charity', 'Медаль "Кайрымдуулук учун" ("За благотворительность")'), ('emgek', 'Медаль "Эмгек ардагери" ("Ветеран труда")'), ('honorary_gramota', 'Почетная грамота Кыргызской Республики')], max_length=100, null=True, verbose_name='Гос. награда')),
                ('honorary_title', models.CharField(blank=True, choices=[('writer', 'Народный писатель Кыргызской Республики'), ('poet', 'Народный поэт Кыргызской Республики'), ('artist', 'Народный художник Кыргызской Республики'), ('actor', 'Народный артист Кыргызской Республики'), ('teacher', 'Народный учитель Кыргызской Республики'), ('z_teacher', 'Заслуженный учитель Кыргызской Республики'), ('z_edu_worker', 'Заслуженный работник образования Кыргызской Республики'), ('z_doctor', 'Заслуженный врач Кыргызской Республики'), ('z_health_worker', 'Заслуженный работник здравоохранения Кыргызской Республики'), ('z_actor', 'Заслуженный артист Кыргызской Республики'), ('z_culture', 'Заслуженный деятель культуры Кыргызской Республики'), ('z_science', 'Заслуженный деятель науки Кыргызской Республики'), ('z_industry', 'Заслуженный работник промышленности Кыргызской Республики'), ('z_agriculture', 'Заслуженный работник сельского хозяйства Кыргызской Республики'), ('z_builder', 'Заслуженный строитель Кыргызской Республики'), ('z_transport', 'Заслуженный работник транспорта Кыргызской Республики'), ('z_communication', 'Заслуженный работник связи Кыргызской Республики'), ('z_geology', 'Заслуженный работник геологической службы Кыргызской Республики'), ('z_services', 'Заслуженный работник сферы обслуживания населения Кыргызской Республики'), ('z_lawyer', 'Заслуженный юрист Кыргызской Республики'), ('z_economist', 'Заслуженный экономист Кыргызской Республики'), ('z_ecology', 'Заслуженный работник охраны природы Кыргызской Республики'), ('z_coach', 'Заслуженный тренер Кыргызской Республики'), ('z_master_sport', 'Заслуженный мастер спорта Кыргызской Республики'), ('z_inventor', 'Заслуженный изобретатель Кыргызской Республики'), ('z_sport_worker', 'Заслуженный работник физической культуры и спорта Кыргызской Республики'), ('z_state_worker', 'Заслуженный работник государственной службы Кыргызской Республики'), ('z_local_gov', 'Заслуженный работник местного самоуправления Кыргызской Республики')], max_length=100, null=True, verbose_name='Почётное звание')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование награды')),
                ('award_date', models.DateField(verbose_name='Дата награждения')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Кем выдано')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('document_number', models.CharField(max_length=100, verbose_name='Приказ №')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='employer.employer')),
            ],
        ),
    ]
