# Generated by Django 5.2.6 on 2025-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Приказ №'),
        ),
    ]
