# Generated by Django 5.2.6 on 2025-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_award_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='faculty',
            field=models.CharField(blank=True, choices=[('atf', 'Аграрно-технический факультет'), ('pedfac', 'Педагогический факультет'), ('filfac', 'Филологический факультет'), ('econom_fac', 'Факультет экономики, менеджмента и физического воспитания')], max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
